### ISSUE TITLE
Obscured class names incorrectly compressed

### ISSUE THREAD

**Issue by benjamin-bader** [square/javapoet#377] opened 2015-12-11 01:03 UTC
I'm seeing an error in generated code that happens when a type reference is [obscured](http://docs.oracle.com/javase/specs/jls/se7/html/jls-6.html#jls-6.4.2) by a member has the same name.  This causes the type name to be obscured in static classes.  JavaPoet doesn't seem to be aware of this, and does not emit a fully-qualified name.

This has come up in a project where we generate Java based on a different DSL that uses Pascal-cased names.  A contrived-but-representative example of the problematic generated code:

```java
// Generated code
final class DataStructure {
  // Assume Foo is an enum that has a static method 'fromCode'
  Foo Foo;

  static class Adapter {
    DataStructure read(BufferedSource source, Builder builder) {
      long code = source.readLong();

      // fails to compile because DataStructure#Foo obscures the type name
      builder.setFoo(Foo.fromCode(code)); 
    }
  }
}
```

The JavaPoet code that generates the above is lengthy and predictable.  The crux is that when the TypeSpec for `Adapter` is emitting, it doesn't seem to be aware of its own context (i.e. of the names in scope), and so `$T` specifiers are compressed incorrectly.

Although there are any number of ways to work around this (change generated field names, use `$L`, un-nest the adapter class, etc), this does seem like a bug.

[0]: http://docs.oracle.com/javase/specs/jls/se7/html/jls-6.html#jls-6.4.2

**Comment by swankjesse** [comment] 2015-12-11 04:14
Test case please!

**Comment by swankjesse** [comment] 2015-12-11 04:14
Ahh, I don't need one. This is a duplicate of our existing bug.

**Comment by swankjesse** [comment] 2015-12-11 04:15
https://github.com/square/javapoet/issues/77

**Closed by swankjesse** 2015-12-11 04:15 UTC

**Comment by benjamin-bader** [comment] 2015-12-11 06:51
Cool, wasn't sure if this was the same issue, but I guess I misread it.  Thanks!
