### ISSUE TITLE
MethodSpec.Builder.returns() should allow a TypeSpec argument.

### ISSUE THREAD

**Issue by briangordon** [square/javapoet#227] opened 2015-02-14 03:06 UTC
I should be able to do this:

``` java
TypeSpec rowTypeSpec = TypeSpec.classBuilder("Row").build();
MethodSpec getRow = MethodSpec.methodBuilder("getRow").returns(rowTypeSpec).build();
```

Instead, I have to do this:

``` java
TypeSpec rowTypeSpec = TypeSpec.classBuilder("Row").build();
TypeName retType = ClassName.get("com.whatever.whatever", "Row");
MethodSpec getRow = MethodSpec.methodBuilder("getRow").returns(retType).build();
```

It's possible that I'm missing something. Is that really the only way for a generated method to return a generated type? If so, I suggest allowing a `TypeSpec` argument to `MethodSpec.Builder.returns()`.

**Comment by JakeWharton** [comment] 2015-02-14 03:54
This is a dupe of #197. And yep, we need something to easy this.

**Closed by JakeWharton** 2015-02-14 03:54 UTC

**Comment by fkleedorfer** [comment] 2020-12-11 10:43
@briangordon I think #816 should fix this, right?
