### ISSUE TITLE
TypeName can not handle recursive generic type variable.

### ISSUE THREAD

**Issue by freetigerliu** [square/javapoet#304] opened 2015-07-07 06:27 UTC
`class Foo<T extends Enum<T>>`

`ParameterizedTypeName.get(Foo.class)` will cause dead loop.

**Comment by sormuras** [comment] 2015-07-07 06:28
Duplicate of https://github.com/square/javapoet/issues/237 ?

**Comment by tbroyer** [comment] 2015-07-07 09:01
Yup, probably the same issue, as `T extends Enum<T>` is recursive (irrespective of the enclosing element)

**Closed by tbroyer** 2015-07-07 09:01 UTC
