### ISSUE TITLE
How can I write  Singleton (Static inner class).

### ISSUE THREAD

**Issue by mcxtzhang** [square/javapoet#539] opened 2017-01-18 16:57 UTC
I want get a Singleton pattern(Static inner class). Like these codes:
```
public class HelloWorld {
  public static HelloWorld getInstance() {
    return InnerClass.INSTANCE;
  }

  private static class InnerClass {
    private static HelloWorld INSTANCE = new HelloWorld();
  }
}
```

At first,my problem is I can not get the type  `HelloWorld ` where I want to use in filed type and return type.

Then I found method `ClassName.bestGuess()`. 
I hope it can take effect.
Then I write :
```
//inner class
        ClassName className = ClassName.bestGuess("HelloWorld");
        FieldSpec INSTANCE = FieldSpec.builder(className, "INSTANCE")
                .addModifiers(Modifier.PRIVATE, Modifier.STATIC)
                .initializer("new $T()", className)
                .build();

        TypeSpec innerClass = TypeSpec.classBuilder("InnerClass")
                .addModifiers(Modifier.PRIVATE, Modifier.STATIC)
                .addField(INSTANCE)
                .build();

        //getInstance method
        MethodSpec methodGetInstance = MethodSpec.methodBuilder("getInstance")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(className)
                .addStatement("return $N.INSTANCE", innerClass)
                .build();


        TypeSpec helloWorld = TypeSpec.classBuilder("HelloWorld")
                .addModifiers(Modifier.PUBLIC)
                .addMethod(methodGetInstance)
                .addType(innerClass)
                .build();


        JavaFile.builder("com.example.helloworld", helloWorld)
                .build()
                .writeTo(System.out);
```

It works.But I want to know which is **the best way** or more elegant way to get it.

My English is not good,Hope u can understand it and reply.

**Comment by tbroyer** [comment] 2017-01-18 17:26
This is actually the same as #294 (which has been marked a duplicate of #197). The suggestion there was to use `ClassName.get("com.example.helloworld", "HelloWorld")`

Your use of `ClassName.bestGuess("HelloWorld")` should return the `HelloWorld` class from [_unnamed package_](https://docs.oracle.com/javase/specs/jls/se7/html/jls-7.html#jls-7.4.2), and those classes [cannot be `import`ed](https://docs.oracle.com/javase/specs/jls/se7/html/jls-7.html#jls-7.5). It might be that JavaPoet generates the appropriate code in this case, but I think that usage is an error/mistake anyway.

**Closed by tbroyer** 2017-01-18 17:26 UTC

**Comment by mcxtzhang** [comment] 2017-01-19 02:47
Thanks.
