### ISSUE TITLE
Can we create static code section in javapoet

### ISSUE THREAD

**Issue by uwudamith** [square/javapoet#381] opened 2015-12-16 18:45 UTC
I want to generate below code bloc inside class.

static {
    // whatever code is needed for initialization goes here
}

How can i do it with javapoet

**Comment by sormuras** [comment] 2015-12-16 19:43
http://stackoverflow.com/questions/34319246/how-to-add-static-section-in-to-java-class-in-javapoet

Issue #381 implements Closeable. ;-)

**Comment by tbroyer** [comment] 2015-12-16 19:51
Dupe of #266 actually.

**Closed by tbroyer** 2015-12-16 19:51 UTC
