### ISSUE TITLE
what should i do about "'addModifiers(javax.lang.model.element.Modifier...)' in 'com.squareup.javapoet.TypeSpec.Builder' cannot be applied to '(javax.lang.model.element.Modifier)'"

### ISSUE THREAD

**Issue by matchparent** [square/javapoet#632] opened 2018-03-13 07:35 UTC
![image](https://user-images.githubusercontent.com/14013349/37328171-20f165f8-26d4-11e8-8c70-a000d181c482.png)

**Comment by JakeWharton** [comment] 2018-03-14 13:41
You're not using something crazy like Java 1.4 are you? Otherwise that seems like an IDE bug. Maybe trying File > Invalidate Caches / Restart?

**Comment by xiaoniaojun** [comment] 2018-03-26 07:37
I also meet this problem，and my gradle setting is here，with android studio 3.0
![Uploading CF6ED12001902DB143060764974DEF13.png…](gradle setting)

**Comment by xiaoniaojun** [comment] 2018-03-26 07:40
I also meet this problem, with android studio 3.0, my gradle setting is here
![cf6ed12001902db143060764974def13](https://user-images.githubusercontent.com/20276875/37892921-0f931af8-310c-11e8-8152-c5377b3653bf.png)

**Comment by matchparent** [comment] 2018-04-03 03:02
![image](https://user-images.githubusercontent.com/14013349/38226898-5a54ce1a-372e-11e8-9bf0-e8380cdde6f5.png)
![image](https://user-images.githubusercontent.com/14013349/38226910-617ceb28-372e-11e8-94d2-7c03d5202f0e.png)
TypeSpec
i think this might be the reason

**Comment by JakeWharton** [comment] 2018-04-03 03:03
Those classes are in the JDK, so either your IDE is broken or you are using an ancient JDK version or are in an Android module. None are problems with this library but with your setup.

**Comment by a3349384** [comment] 2018-04-06 03:01
```
    annotationProcessor project(':compiler')
    //compile project(path: ':compiler')
```

DO NOT use compile!

**Comment by ximen502** [comment] 2018-06-01 12:14
Calm down guys, I encountered this problem too. Well, I use the Eclipse IDE, but when I move these code to IntelliJ IDEA15.0.3, everything is fine. You can try this.

**Comment by Zane96** [comment] 2018-07-29 12:56
1. I have download the new AndroidStudio
2. I have use Java 8
But I still have this problem...

**Comment by amitav13** [comment] 2018-08-23 08:51
Dupe of #139

**Comment by ZhouBey** [comment] 2018-09-03 08:42
same issue

**Comment by tucomel** [comment] 2019-11-09 10:46
same error here, still not fixed? omg

**Comment by lixiaodaoaaa** [comment] 2019-11-22 08:51
> same error here, still not fixed? omg
wow:
##  I sloved by this way !
in the app module 
```
 annotationProcessor project(':compiler')
    //compile project(path: ':compiler')
```
this way is useful for me ,and the android stuido  not has error message 
> a3349384 commented on 6 Apr 2018

this is the capture of my android studio 
![](https://raw.githubusercontent.com/lixiaodaoaaa/publicSharePic/master/20191122165146.png)

**Comment by lixiaodaoaaa** [comment] 2019-11-22 08:57
##  sloved by this way 
before my app build.gralde is like this
```
    implementation project(":processAnnotation")
    annotationProcessor project(":processAnnotation")
```
 ,that will make andorid studio error for the 

```
.addModifiers(Modifier.PUBLIC, Modifier.FINAL);
```
the error is like this
![](https://raw.githubusercontent.com/lixiaodaoaaa/publicSharePic/master/20191122165536.png)

when  I change  build.gradle to this:
```
//    implementation project(":processAnnotation")
    annotationProcessor project(":processAnnotation")
```


the  error message is has gone !
![](https://raw.githubusercontent.com/lixiaodaoaaa/publicSharePic/master/20191122165146.png)


hopes to help you .

**Comment by lixiaodaoaaa** [comment] 2019-11-26 08:58
## I find this way  can work

this just is Android studio bug . Android studio code check error for that .
add this code in your build.gradle in your moudle ,or your app module ,that error will go gone!

```
implementation 'org.checkerframework:checker:2.1.10'
``

add this one ,and the processor module will work 

The whole build.gralde like this:

```
apply plugin: 'java-library'
repositories {
    mavenCentral()
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])


    implementation 'com.squareup:javapoet:1.11.1'
    implementation 'com.google.auto.service:auto-service:1.0-rc6'
    implementation 'org.checkerframework:checker:2.1.10'

    api project(':baseAnnotation')
}

sourceCompatibility = "1.7"
targetCompatibility = "1.7"

tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}
```

the important is 
```
implementation 'org.checkerframework:checker:2.1.10'
```

##  this is caputure of my android studio show
![](https://raw.githubusercontent.com/lixiaodaoaaa/publicSharePic/master/%E7%B2%98%E8%B4%B4%E7%9A%84%E5%9B%BE%E7%89%872019_11_26_16_56.png)

remember only add this  to your build.grale (app or  moudle  both work for you )
this  error just  code check error ,just android stuio app  check error 

```
   implementation 'org.checkerframework:checker:2.1.10'
    provided project(':processAnnotation')
    annotationProcessor project(":processAnnotation")
```
processAnnotation is my process Module .

**Comment by lixiaodaoaaa** [comment] 2019-11-26 09:04
> same error here, still not fixed? omg

look my answer can work!

**Comment by lixiaodaoaaa** [comment] 2019-11-26 09:04
> same issue

look my answer can work!

**Comment by lixiaodaoaaa** [comment] 2019-11-26 09:04
> ```
>     annotationProcessor project(':compiler')
>     //compile project(path: ':compiler')
> ```
> 
> DO NOT use compile!

look my answer can work!

**Comment by lixiaodaoaaa** [comment] 2019-11-26 09:05
> Those classes are in the JDK, so either your IDE is broken or you are using an ancient JDK version or are in an Android module. None are problems with this library but with your setup.

look my answer can work!

**Comment by lixiaodaoaaa** [comment] 2019-11-28 03:02
> You're not using something crazy like Java 1.4 are you? Otherwise that seems like an IDE bug. Maybe trying File > Invalidate Caches / Restart?

##  it's time to close this issue

i just add this  to your build.gradle and it works ,no eror

```
 implementation 'org.checkerframework:checker:2.1.10'
```

**Comment by JakeWharton** [comment] 2019-11-28 03:06
This is not a problem with the library itself but in the specific tooling you are using to consume it which, for whatever reason, may not be exposing the correct APIs. You do not and should not need an additional dependency to resolve this problem, to be clear. I'm closing since there's no action to take.

**Closed by JakeWharton** 2019-11-28 03:06 UTC

**Comment by NapoleonLiuBonapart** [comment] 2020-04-08 08:15
> implementation 'org.checkerframework:checker:2.1

> ## **I find this way can work**
> this just is Android studio bug . Android studio code check error for that .
> add this code in your build.gradle in your moudle ,or your app module ,that error will go gone!
> 
> ```
> implementation 'org.checkerframework:checker:2.1.10'
> ```
> 
> add this one ,and the processor module will work
> 
> The whole build.gralde like this:
> 
> ```
> apply plugin: 'java-library'
> repositories {
>     mavenCentral()
> }
> 
> dependencies {
>     implementation fileTree(dir: 'libs', include: ['*.jar'])
>     implementation 'com.squareup:javapoet:1.11.1'
>     implementation 'com.google.auto.service:auto-service:1.0-rc6'
>     implementation 'org.checkerframework:checker:2.1.10'
> 
>     api project(':baseAnnotation')
> }
> 
> sourceCompatibility = "1.7"
> targetCompatibility = "1.7"
> 
> tasks.withType(JavaCompile) {
>     options.encoding = "UTF-8"
> }
> ```
> 
> ### the important is
> ```
> implementation 'org.checkerframework:checker:2.1.10'
> ```
> 
> ## this is caputure of my android studio show
> ![](https://raw.githubusercontent.com/lixiaodaoaaa/publicSharePic/master/%E7%B2%98%E8%B4%B4%E7%9A%84%E5%9B%BE%E7%89%872019_11_26_16_56.png)
> 
> remember only add this to your build.grale (app or moudle both work for you )
> this error just code check error ,just android stuio app check error
> 
> below is my app module's build.gradle file like this .
> you can add in your app moudle,that also can work
> 
> ```
>    implementation 'org.checkerframework:checker:2.1.10'
>     provided project(':processAnnotation')
>     annotationProcessor project(":processAnnotation")
> ```
> 
> processAnnotation is my process Module

This work for me.
