### ISSUE TITLE
Provide a simple way to generate Java source code with a specific encoding

### ISSUE THREAD

**Issue by saw303** [square/javapoet#564] opened 2017-06-08 09:12 UTC
Currently `com.squareup.javapoet.JavaFile` provides the following method to write the Java source code to the file system.

- `writeTo(Appendable)`
- `writeTo(Path)`
- `writeTo(File)`
- `writeTo(Filer)`

The methods `writeTo(Path)` and `writeTo(File)` provide a very nice way to write code to a standard directory. The do 

- create all directories (according to the package name)
- and create the Java file itself in the correct directory structure

The downside of this convenient method is that they choose the default encoding of the current Java virtual machine when writing the Java source code into the target file.

In our build we'd like to make sure all our source code is `UTF-8` encoded. Therefore it would be very handy to have convenience methods such as:

- `writeTo(Path, Charset)`
- `writeTo(File, Charset)`

**Comment by sormuras** [comment] 2017-06-08 09:16
Since [1.8.0](https://github.com/square/javapoet/blob/master/CHANGELOG.md#javapoet-180-2016-11-09) JavaPoet always uses UTF-8:
_Fix: Always write UTF-8. Previously JavaPoet would use the system default charset which was potentially inconsistent across environments._

**Comment by tbroyer** [comment] 2017-06-08 10:52
Dupe of #473

**Closed by tbroyer** 2017-06-08 10:52 UTC

**Comment by saw303** [comment] 2017-06-09 04:31
Good to hear that JavaPoet uses UTF-8 in general. 

But this issue asks about more flexibility. I as programmer would like to tell JavaPoet what encoding to use. There are projects that are not using UTF-8 as source code encoding. In these projects I cannot use JavaPoet at the current state.

If you do not like to change the API you could introduce an SPI using Java's [ServiceLoader](https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html) to provide a way to change the default encoding.

**Comment by ronshapiro** [comment] 2017-06-09 11:23
JavaFile.toString() gives you the file contents as a string, then you could
call getBytes yourself with whatever charset you want

**Comment by saw303** [comment] 2017-06-09 11:33
I agree. That does the job.
