### ISSUE TITLE
Float and Char Literals generated wrongly

### ISSUE THREAD

**Issue by marschall** [square/javapoet#587] opened 2017-11-17 21:17 UTC
The following statement 

```java
aBuilder.addStatement("return $L", Character.valueOf(2))
```

produces this code

```java
return 2;
```

but should produce

```java
return '2';
```

the same with

```java
aBuilder.addStatement("return $L", Float.valueOf(2))
```

produces this code

```java
return 2.0;
```

which does not compile if the return type is `float`

but should produce

```java
return 2.0f;
```

**Comment by sormuras** [comment] 2017-11-17 21:25
Duplicate of #581

**Closed** 2017-11-18 08:30 UTC
